### PR TITLE
Target NLog 4.5.0 and removed BETA suffix

### LINKED ISSUE #62: Packaging for NLog appender is setting "beta" version for Common
The NLog appender is currently packed with the following command:

```
dotnet pack .\SumoLogic.Logging.NLog\SumoLogic.Logging.NLog.csproj --output "$(Convert-Path .)\SumoLogic.Logging.Nuget" --configuration Release /p:Version=$fin_ver-beta1
```

This appears to be causing the full dependency chain to get tagged with `-beta1` package version, including SumoLogic.Logging.Common. The goal is for only the NLog portion to be tagged as beta.

image

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves  #62

### CODE REVIEW

**Comment by latkin** [comment]
I think https://github.com/SumoLogic/sumologic-net-appenders/pull/63 should have fixed #62?

I have not yet built and published new packages with that fix, sorry about that.

**Comment by latkin** [comment]
Oh but now NLog has full (non beta, non RC) support https://www.nuget.org/packages/NLog/4.5.0 got it. Yeah this makes sense. Will merge this soon.

**Comment by snakefoot** [comment]
@latkin Yes #63 was the temporary fix until NLog was free of beta.

**Comment by snakefoot** [comment]
@latkin Is something blocking the merge?

**Comment by latkin** [comment]
@snakefoot just absent-mindedness 😖 thanks for the reminder

**Comment by snakefoot** [comment]
@latkin  Will there also be a non-beta Nuget package of SumoLogic.Logging.NLog ?

**Pull request merged**
