### PR TITLE
Allow the ability to flush any remaining logs that are buffered and haven't been sent

### PR DESCRIPTION
**Pull request by jakejscott**
If using the `BufferedSumoLogicAppender` when it shuts down logs are not being flushed at all. With this fix you can get all the `IFlushable` objects and call flush on them.

```
public static void Main()
        {
            try
            {
                int numMessages = 3;
                for (int i = 0; i < numMessages; i++)
                {
                    log4netLog.Info("info " + i);
                }
            }
            finally
            {
                FlushLogs();
            }

            Console.ReadKey();
        }

        private static void FlushLogs()
        {
            var appenderSkeletons = LogManager
                .GetAllRepositories()
                .SelectMany(r => r.GetAppenders())
                .OfType<IFlushable>()
                .ToArray();

            foreach (var appender in appenderSkeletons)
            {
                try
                {
                    appender.Flush(10000);
                }
                catch
                {
                    // Cannot do anything here
                }
            }
        }
```

### CODE REVIEW

**Comment by bin3377** [comment]
Thanks for the contribution! The change is make sense for me. I will do some test and merge it

**Comment by jakejscott** [comment]
Are you going to publish a new nuget package?

**Comment by bin3377** [comment]
yes. it's on https://www.nuget.org/packages/SumoLogic.Logging.Serilog/ now but I think I may push another version to do some adjustment like using consistent version number format...

**Comment by jakejscott** [comment]
This commit was a change for log4net :) Which hasn't been updated yet in Nuget
https://www.nuget.org/packages/SumoLogic.Logging.Log4Net/

**Comment by bin3377** [comment]
ahh... sorry I just confused myself. Yes, will push a new version for all packages after I fix the appveyor building and couple of doc nits

**Comment by bin3377** [comment]
FYI - 1.0.0.8 nuget released with this change

**Pull request merged**
