### PR TITLE
Locking on a private dummy object to conform to correct usage of locking

### PR DESCRIPTION
**Pull request by billpratt**
To prevent potential dead locks, it is recommended to not use MethodImplOptions.Synchronized nor lock(this). Instead, you should lock on a private dummy object. 

See here for more info: https://blogs.msdn.microsoft.com/bclteam/2004/01/20/lock-vs-methodimploptions-synchronized-kit-george/

### CODE REVIEW

**Comment by billpratt** [comment]
Hello,

Has anyone had a chance to review this and/or provide feedback?

**Comment by billpratt** [comment]
@latkin any feedback here?

**Comment by billpratt** [comment]
ping. Any feedback?

**Comment by latkin** [comment]
This LGTM for locking issue, but I'd like to merge that separately from all of the .NET Standard stuff.

**Comment by billpratt** [comment]
@latkin I'm going to close these PRs and submit cleaner individuals

**Pull request closed without merging**
