### PR TITLE
Projects targeting .NET Standard

### PR DESCRIPTION
**Pull request by billpratt**
I have created a new solution named SumoLogic.Logging.NetStandard.sln that contains projects targeting [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) for the following existing projects:

- SumoLogic.Logging.Common
- SumoLogic.Logging.Log4Net
- SumoLogic.Logging.NLog

This will allow developers targeting .NET Core to start using the SumoLogic appenders. You'll notice that each of these projects contain no C# classes. If you examine the project.json file in each of these projects, you'll see I'm including *.cs from each of its sister projects in SumoLogic.Logging.sln when building against .NET Standard. This approach is similar to how Log4Net and MongoDB C# drivers are targeting .NET Standard until the new csproj structure RTMs.

I had to make a few minor tweaks in order for these projects to build, such as: 

- replacing System.Timers.Timer with System.Threading.Timer (suggested replacement)
- changing FlushingAccuracy from **long** to **int** since Timer takes in an **int**

I have also included a sample ASP.NET Core application, SumoLogic.Logging.NLog.Examples.AspNetCore, that uses the SumoLogic.Logging.NLog project and verified logs are being posted.

The latest Log4Net targets .NET Standard, and NLog's version is currently in beta. I will keep this PR up to date as NLog's version changes.

I would appreciate any feedback/questions/concerns.

Thanks!

### CODE REVIEW

**Comment by mirthy** [comment]
👍

**Comment by latkin** [comment]
Hi @billpratt, thanks for the work on this! Would you care to join the conversation at https://github.com/SumoLogic/sumologic-net-appenders/issues/19? We are discussing possibilities for .NET core/.NET standard/portable libraries, and I'd appreciate your input.

As some quick initial feedback, I'd like the 3 (mostly unrelated) changes in this PR to be split into 3 separate PRs. The locking fix I'd be happy to merge straight away while we sort out targeting stuff.

**Comment by billpratt** [comment]
Sure thing. I'll work on getting those split to 3 separate PRs.

**Comment by billpratt** [comment]
I have move all of the code changes to separate PRs and confirmed locally that the NetStandard solution still builds. Would you like a separate PR for the NET Standard solution/projects for review?

**Pull request closed without merging**
